version: 2
jobs:
  test:
    working_directory: ~/documentation
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout
      - run: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - restore_cache:
          keys:
            - v4-node_modules-{{ checksum "package.json" }}
            - v4-node_modules-
      - run:
          command: npm install
          no_output_timeout: 20m
      - save_cache:
          key: v4-node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
      - persist_to_workspace:
          root: ~/documentation
          paths: .

  publish:
    working_directory: ~/documentation
    docker:
      - image: circleci/node:dubnium
    steps:
      - attach_workspace:
          at: ~/documentation
      - run: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - run:
          name: publish
          command: npm publish
          no_output_timeout: 40m

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:  # required since `publish` has tag filters AND requires `test`
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
