import React from 'react';
import { BemTags } from '@scipe/ui';

const bem = new BemTags('@sa', '@documentation');

export default class Processing extends React.Component {
  render() {
    return (
      <section
        id="processing-normalization"
        className={bem`processing @__section`}
      >
        <h2 className={bem`@__default-ui-type--headline`}>
          Processing and normalization
        </h2>

        <ol>
          <li>Manifest content (JSON-LD) is converted to RDF.</li>
          <li>
            For each RDFa / DS3 file present in the manifest (if any) additional
            RDF triples are added to the graph. In case of conflicts, values
            coming from the RDFa / DS3 files overwrite the ones coming directly
            from the manifest (JSON-LD).
          </li>
          <li>
            A unified manifest is regenerated by serializing the RDF graph into
            JSON-LD (in{' '}
            <a href="https://www.w3.org/TR/json-ld/#flattened-document-form">
              flattened
            </a>{' '}
            and{' '}
            <a href="https://www.w3.org/TR/json-ld/#compacted-document-form">
              compacted
            </a>{' '}
            document form), ensuring that the content is normalized.
          </li>
        </ol>
      </section>
    );
  }
}
